//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baeckerei40
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestellung
    {
        public int BestellID { get; set; }
        public System.DateTime Abholdatum { get; set; }
        public int KundenID { get; set; }
    }
}
