//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baeckerei40
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkte
    {
        public int ProduktID { get; set; }
        public string Produktname { get; set; }
        public string Produktpreis { get; set; }
    }
}
