//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baeckerei40
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rohstoffe
    {
        public int RohstoffID { get; set; }
        public string Rohstoffname { get; set; }
        public string Rohstoffeinheit { get; set; }
        public double Rohstoffpreis { get; set; }
        public int Lagermenge { get; set; }
    }
}
