//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baeckerei40_asp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class baeckerei40Entities : DbContext
    {
        public baeckerei40Entities()
            : base("name=baeckerei40Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bestellungen> Bestellungen { get; set; }
        public virtual DbSet<Kunden> Kunden { get; set; }
        public virtual DbSet<Produkte> Produkte { get; set; }
        public virtual DbSet<ProdukteInBestellungen> ProdukteInBestellungen { get; set; }
        public virtual DbSet<Rohstoffe> Rohstoffe { get; set; }
        public virtual DbSet<RohstoffeInProdukte> RohstoffeInProdukte { get; set; }
    }
}
