//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baeckerei40_asp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produkte()
        {
            this.ProdukteInBestellungen = new HashSet<ProdukteInBestellungen>();
            this.RohstoffeInProdukte = new HashSet<RohstoffeInProdukte>();
        }
    
        public int ProduktID { get; set; }
        public string Produktname { get; set; }
        public string Produktpreis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdukteInBestellungen> ProdukteInBestellungen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RohstoffeInProdukte> RohstoffeInProdukte { get; set; }
    }
}
