//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baeckerei40_asp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdukteInBestellungen
    {
        public int BestellungEnthaeltID { get; set; }
        public string BestellMenge { get; set; }
        public int BestellID { get; set; }
        public int ProduktID { get; set; }
    
        public virtual Bestellungen Bestellungen { get; set; }
        public virtual Produkte Produkte { get; set; }
    }
}
