//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baeckerei40_asp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rohstoffe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rohstoffe()
        {
            this.RohstoffeInProdukte = new HashSet<RohstoffeInProdukte>();
        }
    
        public int RohstoffID { get; set; }
        public string Rohstoffname { get; set; }
        public string Rohstoffeinheit { get; set; }
        public double Rohstoffpreis { get; set; }
        public int Lagermenge { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RohstoffeInProdukte> RohstoffeInProdukte { get; set; }
    }
}
